name: Node.js CI

on: #When to run
  push: #What to run
    branches: [main, dev] #Where to run
  pull_request: #What to run
    branches: [main, dev] #Where to run

jobs: #What to automate
  build:
    runs-on: ubuntu-latest #operating system

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps: #step to run the automation
      - name: Checkout
        uses: actions/checkout@v2 #navigate GitHub action to the branch(es) where the 'on' occur

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1 #set up the environment in the 'matrix'
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run NPM Install
        run: npm install
      
      - name: Run NPM test
        run: npm test